In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt


In [2]:
dataset=pd.read_csv(r'C:\Users\User\Desktop\IM PR & ML\ML Couse\video 6\heart_risk_level_predictor\cardio_dataset.csv').values

In [5]:
print(dataset)
print(dataset.shape)

[[  1.   48.  236.  ...   1.    0.    1.1]
 [  0.   48.  260.  ...   1.    1.    7. ]
 [  0.   44.  187.  ...   1.    0.    7. ]
 ...
 [  0.   65.  212.  ...   0.    0.   30.6]
 [  0.   66.  184.  ...   0.    0.   23.8]
 [  1.   45.  203.  ...   1.    0.    1. ]]
(6644, 8)


In [10]:
data=dataset[:,0:7]
target=dataset[:,7]
print('data:',data)
print('target:',target)

data: [[  1.  48. 236. ...   0.   1.   0.]
 [  0.  48. 260. ...   0.   1.   1.]
 [  0.  44. 187. ...   1.   1.   0.]
 ...
 [  0.  65. 212. ...   1.   0.   0.]
 [  0.  66. 184. ...   0.   0.   0.]
 [  1.  45. 203. ...   0.   1.   0.]]
target: [ 1.1  7.   7.  ... 30.6 23.8  1. ]


In [14]:
from sklearn.model_selection import train_test_split
train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.1)

In [16]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(train_data,train_target)

LinearRegression()

In [19]:
print('coef:',model.coef_)
print('a0:',model.intercept_)
predicted_target=model.predict(test_data)
print('Actaul:',test_target[:10])
print('Predicted:',predicted_target[:10])


coef: [-4.86524304  0.73028167  0.02596512 -0.07033133  5.86833545 -5.30521383
 11.12080825]
a0: -27.708695408726733
Actaul: [ 0.3  6.1 43.5 11.8  2.1  4.7  3.9 15.5  0.4 17.4]
Predicted: [-1.08201486  9.47058596 27.70497878 17.45610928  2.06850687 10.20492736
 15.08363364 25.42081552 -6.27322147 25.24702738]


In [20]:
from sklearn.metrics import r2_score

r2=r2_score(test_target,predicted_target)
print('r2:',r2)

r2: 0.7422481289866356


In [21]:
import joblib

joblib.dump(model,'heart-risk-reg-model.sav')

['heart-risk-reg-model.sav']